# Generated by Django 2.1.3 on 2019-02-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='blogpics'),
        ),
    ]
